name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v1

    - name: Cache Text
      uses: actions/cache@v1
      with:
        path: test
        key: ${{ runner.os }}-text2-${{ hashFiles('**/README.md') }}
 
    - name: Create Text
      run: | 
        mkdir -p test
        echo test >> test/text.txt
