name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 4 * * 1-5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v1

    - name: Cache Text
      uses: actions/cache@v1
      with:
        path: test
        key: ${{ runner.os }}-text-${{ hashFiles('**/README.md') }}

    - name: Create Text
      run: |
        mkdir -p test
        echo test >> test/text.txt
        cd test
        ls
 
     - name: Test
      run: |
        ls